package com.cn.entity;

/**
 * TOrderItem generated by MyEclipse Persistence Tools
 */

public class TOrderItem implements java.io.Serializable {

	// Fields

	private Integer orderItemId;

	private Integer orderId;

	private Integer goodsId;

	private Integer goodsQuantity;

	private TGoods goods;// 数据库没有，自己加的

	// Constructors

	/** default constructor */
	public TOrderItem() {
	}

	/** full constructor */
	public TOrderItem(Integer orderId, Integer goodsId, Integer goodsQuantity) {
		this.orderId = orderId;
		this.goodsId = goodsId;
		this.goodsQuantity = goodsQuantity;
	}

	public Integer getOrderItemId() {
		return orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public Integer getGoodsQuantity() {
		return goodsQuantity;
	}

	public void setGoodsQuantity(Integer goodsQuantity) {
		this.goodsQuantity = goodsQuantity;
	}

	public TGoods getGoods() {
		return goods;
	}

	public void setGoods(TGoods goods) {
		this.goods = goods;
	}

	// Property accessors

}